[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.140"
sqlx = {version="0.8.3", features=["runtime-tokio"]}
tokio = "1.44.1"
