[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.1"
# tokio-rusqlite = {version = "0.6.0", features = ["bundled"]}
bcrypt = "0.17"
mysql_async = "0.35.1"
